# Generated by Django 3.2.7 on 2021-11-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('baner', models.ImageField(upload_to='document', verbose_name='تصویر')),
                ('status', models.BooleanField(default=False, verbose_name='تایید')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='call_price',
            field=models.IntegerField(default=0, verbose_name='نرخ تماس'),
        ),
        migrations.AlterField(
            model_name='author',
            name='msg_price',
            field=models.IntegerField(default=0, verbose_name='نرخ پیام'),
        ),
    ]
