# Generated by Django 3.2.7 on 2021-11-28 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20211128_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userDocument', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
