# Generated by Django 3.2.7 on 2021-12-04 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AuthorDoctorId', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
    ]
