# Generated by Django 3.2.7 on 2021-12-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='shaba',
            field=models.CharField(max_length=50, null=True, verbose_name='شبا'),
        ),
    ]
