# Generated by Django 3.2.7 on 2021-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='track_id',
            field=models.CharField(max_length=250, null=True, verbose_name='کد رهگیری آیدی پی'),
        ),
    ]
