# Generated by Django 3.2.7 on 2021-12-19 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_alter_transaction_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='requestUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestUserId', to=settings.AUTH_USER_MODEL),
        ),
    ]
