# Generated by Django 3.2.7 on 2021-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_follower_requestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=True, null=True, verbose_name='دیده شده'),
        ),
    ]
