# Generated by Django 3.2.7 on 2021-12-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.IntegerField(default=1, null=True, verbose_name='دسته بندی'),
        ),
    ]
