# Generated by Django 3.2.7 on 2021-12-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
