# Generated by Django 3.2.7 on 2021-12-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_message_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authorLink',
            field=models.CharField(max_length=200, null=True, verbose_name='ادرس مشاور'),
        ),
    ]
