# Generated by Django 3.2.7 on 2022-02-24 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_exam_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='AuthorId',
            new_name='authorId',
        ),
        migrations.AddField(
            model_name='question',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userQuestion', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.CharField(max_length=250, null=True, verbose_name='جواب'),
        ),
    ]
