# Generated by Django 3.2.7 on 2022-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220224_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to='question', verbose_name='بنر'),
        ),
    ]
