# Generated by Django 3.2.7 on 2022-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_question_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='optionA',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الف'),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionB',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionC',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ج'),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionD',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='د'),
        ),
    ]
