# Generated by Django 3.2.7 on 2022-02-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220226_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='question',
        ),
        migrations.AddField(
            model_name='exam',
            name='questionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionId', to='api.question', verbose_name='سوال'),
        ),
    ]
