# Generated by Django 3.2.7 on 2022-03-17 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_auto_20220227_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='نام آزمون')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('e', 'ویرایش شده')], default='d', max_length=1, verbose_name='وضعیت')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='اسلاگ')),
                ('amount', models.IntegerField(default=0, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorCreateExam', to='api.author', verbose_name='مشاور')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userIdauthorCreateExam', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='VisitExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorAnswer', models.CharField(max_length=250, null=True, verbose_name='پاسخ مشاور')),
                ('active', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examVisitId', to='api.createexam', verbose_name='سوال')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userVisitedExam', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='متن سوال')),
                ('type', models.BooleanField(default=True, verbose_name='چهارگزینه ای')),
                ('optionA', models.CharField(blank=True, max_length=250, null=True, verbose_name='الف')),
                ('optionB', models.CharField(blank=True, max_length=250, null=True, verbose_name='ب')),
                ('optionC', models.CharField(blank=True, max_length=250, null=True, verbose_name='ج')),
                ('optionD', models.CharField(blank=True, max_length=250, null=True, verbose_name='د')),
                ('baner', models.ImageField(blank=True, null=True, upload_to='question', verbose_name='بنر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionForExamId', to='api.createexam', verbose_name='سوال')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='شماره تماس')),
                ('visitTime', models.DateTimeField(verbose_name='زمان ویزیت')),
                ('active', models.BooleanField(default=False, verbose_name='تایید مشاور')),
                ('autoDial', models.BooleanField(default=False, verbose_name='تماس خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('AuthorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorWasVisited', to='api.author', verbose_name='کد ویزیت مشاور')),
                ('AuthorUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorUserIdWasVisited', to=settings.AUTH_USER_MODEL, verbose_name='کد کاربری مشاور')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRequest', to=settings.AUTH_USER_MODEL, verbose_name='کاربر متقاضی')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVisitedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250, null=True, verbose_name='جواب')),
                ('examId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examId', to='api.createexam', verbose_name='تست')),
                ('questionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answerQuestionId', to='api.questionsexam', verbose_name='سوال')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userAnsweredQuestion', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
