# Generated by Django 3.2.7 on 2021-12-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='stars',
            field=models.IntegerField(null=True, verbose_name='ستاره'),
        ),
    ]
