# Generated by Django 3.2.7 on 2021-12-05 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('subject', models.CharField(max_length=250, verbose_name='عنوان')),
                ('content', models.TextField(max_length=2500, verbose_name='محتوا')),
                ('baner', models.ImageField(null=True, upload_to='ticket', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketUserId', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
