# Generated by Django 3.2.7 on 2021-12-06 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_rename_blog_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sendTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendTicketToUserId', to=settings.AUTH_USER_MODEL, verbose_name='ارسال از ادمین به'),
        ),
    ]
