# Generated by Django 3.2.7 on 2021-12-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_sendto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.BooleanField(default=False, max_length=1, verbose_name='وضعیت'),
        ),
    ]
